### ISSUE TITLE
Enable automatically when opening supported files

### ISSUE THREAD

**Issue by salastro** [skywind3000/vim-rt-format#2]
Hello,

I wanted to enable the plugin automatically whenever I am in a supported file, or at least in files that I would like the plugin to work in. I did not find anything explicit about it in the code or the README, pardon me if there was another place I should have looked for.
I have tried `autocmd BufNewFile,BufRead *.py RTFormatEnable` to enable it when opening python files. However, it did not work, and I was not able, by any means, to know where was the problem.

Thanks for the time.

**Comment by nigo81** [comment]
autocmd BufEnter *.py :RTFormatEnable
set shortmess=a
set cmdheight=2

**Comment by salastro** [comment]
> autocmd BufEnter *.py :RTFormatEnable

This line is working perfectly, thanks.
